namespace FireAlt.BLinq.Generators.Templates
{
    internal sealed class AccumulatorTemplate : TextTemplate
    {
        private readonly AccumulatorData accumulator;

        public AccumulatorTemplate(AccumulatorData accumulator)
        {
            this.accumulator = accumulator;
        }

        protected override void Render()
        {
            Header();
            Block("namespace FireAlt.BLinq", () =>
            {
                Accumulator();
                WriteLine();
                SumAverageExtensions();
            });
        }

        private void Header()
        {
            WriteLine("// <auto-generated/>");
            WriteLine("#nullable enable");
            WriteLine();
        }

        private void Accumulator()
        {
            var addExpression = $"({accumulator.FullTypeName})(total + value)";
            var divideExpression = $"({accumulator.FullTypeName})(total / {accumulator.CountExpression})";

            Block($"public struct {accumulator.StructName} : global::FireAlt.BLinq.IAccumulator<{accumulator.FullTypeName}>", () =>
            {
                AggressiveInlining();
                Block($"public {accumulator.FullTypeName} Add(in {accumulator.FullTypeName} total, in {accumulator.FullTypeName} value)", () =>
                {
                    WriteLine($"return {addExpression};");
                });

                WriteLine();
                AggressiveInlining();
                Block($"public {accumulator.FullTypeName} Divide(in {accumulator.FullTypeName} total, uint count)", () =>
                {
                    WriteLine($"return {divideExpression};");
                });
            });
        }

        private void SumAverageExtensions()
        {
            Block("public static partial class BLinqExtensions", () =>
            {
                SumSourceExtension();
                WriteLine();
                SumSelectorExtension();
                WriteLine();
                AverageSourceExtension();
                WriteLine();
                AverageSelectorExtension();
            });
        }

        private void SumSourceExtension()
        {
            WriteLine("/// <summary>");
            WriteLine("/// Returns the sum of the query using the default accumulator.");
            WriteLine("/// </summary>");
            WriteLine("/// <param name=\"source\">Source query.</param>");
            WriteLine("/// <returns>The sum of all elements.</returns>");
            AggressiveInlining();
            WriteLine($"public static {accumulator.FullTypeName} Sum<TEnumerator>(this global::FireAlt.BLinq.Query<TEnumerator, {accumulator.FullTypeName}> source)");
            PushIndent();
            WriteLine($"where TEnumerator : unmanaged, global::FireAlt.BLinq.IQueryEnumerator<{accumulator.FullTypeName}>");
            PopIndent();
            Block(() =>
            {
                WriteLine($"return source.Sum<{accumulator.FullTypeName}, TEnumerator, global::FireAlt.BLinq.{accumulator.StructName}>();");
            });
        }

        private void SumSelectorExtension()
        {
            WriteLine("/// <summary>");
            WriteLine("/// Returns the sum of the projected values using the default accumulator.");
            WriteLine("/// </summary>");
            WriteLine("/// <param name=\"source\">Source query.</param>");
            WriteLine("/// <param name=\"selector\">Selector used to project each element before summing.</param>");
            WriteLine("/// <param name=\"_\">Unused default parameter used to guide overload resolution.</param>");
            WriteLine("/// <returns>The sum of the projected values.</returns>");
            AggressiveInlining();
            WriteLine($"public static {accumulator.FullTypeName} Sum<TSource, TEnumerator, TSelector>(this global::FireAlt.BLinq.Query<TEnumerator, TSource> source, TSelector selector, {accumulator.FullTypeName} _ = default)");
            PushIndent();
            WriteLine("where TSource : unmanaged");
            WriteLine("where TEnumerator : unmanaged, global::FireAlt.BLinq.IQueryEnumerator<TSource>");
            WriteLine($"where TSelector : unmanaged, global::FireAlt.BLinq.ISelector<TSource, {accumulator.FullTypeName}>");
            PopIndent();
            Block(() =>
            {
                WriteLine($"return source.Sum<TSource, {accumulator.FullTypeName}, TEnumerator, TSelector, global::FireAlt.BLinq.{accumulator.StructName}>(selector);");
            });
        }

        private void AverageSourceExtension()
        {
            WriteLine("/// <summary>");
            WriteLine("/// Returns the average of the query using the default accumulator.");
            WriteLine("/// </summary>");
            WriteLine("/// <param name=\"source\">Source query.</param>");
            WriteLine("/// <returns>The average of all elements.</returns>");
            AggressiveInlining();
            WriteLine($"public static {accumulator.FullTypeName} Average<TEnumerator>(this global::FireAlt.BLinq.Query<TEnumerator, {accumulator.FullTypeName}> source)");
            PushIndent();
            WriteLine($"where TEnumerator : unmanaged, global::FireAlt.BLinq.IQueryEnumerator<{accumulator.FullTypeName}>");
            PopIndent();
            Block(() =>
            {
                WriteLine($"return source.Average<{accumulator.FullTypeName}, TEnumerator, global::FireAlt.BLinq.{accumulator.StructName}>();");
            });
        }

        private void AverageSelectorExtension()
        {
            WriteLine("/// <summary>");
            WriteLine("/// Returns the average of the projected values using the default accumulator.");
            WriteLine("/// </summary>");
            WriteLine("/// <param name=\"source\">Source query.</param>");
            WriteLine("/// <param name=\"selector\">Selector used to project each element before averaging.</param>");
            WriteLine("/// <param name=\"_\">Unused default parameter used to guide overload resolution.</param>");
            WriteLine("/// <returns>The average of the projected values.</returns>");
            AggressiveInlining();
            WriteLine($"public static {accumulator.FullTypeName} Average<TSource, TEnumerator, TSelector>(this global::FireAlt.BLinq.Query<TEnumerator, TSource> source, TSelector selector, {accumulator.FullTypeName} _ = default)");
            PushIndent();
            WriteLine("where TSource : unmanaged");
            WriteLine("where TEnumerator : unmanaged, global::FireAlt.BLinq.IQueryEnumerator<TSource>");
            WriteLine($"where TSelector : unmanaged, global::FireAlt.BLinq.ISelector<TSource, {accumulator.FullTypeName}>");
            PopIndent();
            Block(() =>
            {
                WriteLine($"return source.Average<TSource, {accumulator.FullTypeName}, TEnumerator, TSelector, global::FireAlt.BLinq.{accumulator.StructName}>(selector);");
            });
        }
    }
}
