namespace FireAlt.BLinq.Generators.Templates
{
    using System.Collections.Immutable;

    internal sealed class QueryCollectionExtensionsTemplate : TextTemplate
    {
        private readonly ImmutableArray<QueryExtensionData> queryExtensions;

        public QueryCollectionExtensionsTemplate(ImmutableArray<QueryExtensionData> queryExtensions)
        {
            this.queryExtensions = queryExtensions;
        }

        protected override void Render()
        {
            Header();
            Block("namespace FireAlt.BLinq", () =>
            {
                Block("public static partial class BLinqExtensions", () =>
                {
                    for (var i = 0; i < queryExtensions.Length; i++)
                    {
                        if (i != 0)
                        {
                            WriteLine();
                        }

                        QueryExtension(queryExtensions[i]);
                    }
                });

                for (var i = 0; i < queryExtensions.Length; i++)
                {
                    WriteLine();
                    IndexerEnumerator(queryExtensions[i]);
                }
            });
        }

        private void Header()
        {
            WriteLine("// <auto-generated/>");
            WriteLine("#nullable enable");
            WriteLine("using Unity.Collections.LowLevel.Unsafe;");
            WriteLine();
        }

        private void QueryExtension(QueryExtensionData queryExtension)
        {
            var typeParameterList = queryExtension.TypeParameterNames.Length == 0
                ? string.Empty
                : $"<{string.Join(", ", queryExtension.TypeParameterNames)}>";
            var enumeratorType = $"{queryExtension.IndexerEnumeratorTypeName}{typeParameterList}";
            var queryType = $"global::FireAlt.BLinq.Query<{enumeratorType}, {queryExtension.ItemTypeName}>";
            var enumeratorExpression = $"new {enumeratorType}(collection)";

            AggressiveInlining();
            WriteLine($"public static {queryType} AsQuery{typeParameterList}(this {queryExtension.CollectionTypeName} collection)");
            PushIndent();
            foreach (var constraintClause in queryExtension.ConstraintClauses)
            {
                WriteLine(constraintClause);
            }

            PopIndent();
            Block(() =>
            {
                if (queryExtension.LengthExpression.Length == 0)
                {
                    WriteLine($"return new {queryType}({enumeratorExpression});");
                }
                else
                {
                    WriteLine($"return new {queryType}({enumeratorExpression});");
                }
            });
        }

        private void IndexerEnumerator(QueryExtensionData queryExtension)
        {
            var typeParameterList = queryExtension.TypeParameterNames.Length == 0
                ? string.Empty
                : $"<{string.Join(", ", queryExtension.TypeParameterNames)}>";

            WriteLine($"public struct {queryExtension.IndexerEnumeratorTypeName}{typeParameterList} : global::FireAlt.BLinq.IQueryEnumerator<{queryExtension.ItemTypeName}>");
            PushIndent();
            foreach (var constraintClause in queryExtension.ConstraintClauses)
            {
                WriteLine(constraintClause);
            }

            PopIndent();
            Block(() =>
            {
                WriteLine($"private {queryExtension.CollectionTypeName} _collection;");
                WriteLine($"private {queryExtension.EnumeratorTypeName} _enumerator;");
                WriteLine();

                Block($"public {queryExtension.IndexerEnumeratorTypeName}({queryExtension.CollectionTypeName} collection)", () =>
                {
                    WriteLine("_collection = collection;");
                    WriteLine($"_enumerator = {queryExtension.EnumeratorExpression};");
                });
                WriteLine();

                AggressiveInlining();
                Block("public bool TryGetNonEnumeratedCount(out int count)", () =>
                {
                    if (queryExtension.LengthExpression.Length == 0)
                    {
                        WriteLine("count = 0;");
                        WriteLine("return false;");
                        return;
                    }

                    WriteLine($"count = {queryExtension.LengthExpression.Replace("collection", "_collection")};");
                    WriteLine("return true;");
                });
                WriteLine();

                AggressiveInlining();
                Block($"public unsafe bool TryGetSpan(out global::System.ReadOnlySpan<{queryExtension.ItemTypeName}> span)", () =>
                {
                    if (!queryExtension.HasIndexer)
                    {
                        WriteLine("span = default;");
                        WriteLine("return false;");
                        return;
                    }

                    WriteLine($"span = new global::System.ReadOnlySpan<{queryExtension.ItemTypeName}>(");
                    PushIndent();
                    WriteLine($"{GetUnsafePointerExpression(queryExtension)},");
                    WriteLine($"{queryExtension.LengthExpression.Replace("collection", "_collection")});");
                    PopIndent();
                    WriteLine("return true;");
                });
                WriteLine();

                AggressiveInlining();
                Block($"public unsafe bool TryGetElementAt(int index, out {queryExtension.ItemTypeName} value)", () =>
                {
                    if (!queryExtension.HasIndexer)
                    {
                        WriteLine("value = default;");
                        WriteLine("return false;");
                        return;
                    }

                    Block($"if ((uint)index >= (uint){queryExtension.LengthExpression.Replace("collection", "_collection")})", () =>
                    {
                        WriteLine("value = default;");
                        WriteLine("return false;");
                    });
                    WriteLine();
                    WriteLine($"value = {GetElementAtExpression(queryExtension)};");
                    WriteLine("return true;");
                });
                WriteLine();

                Block($"public {queryExtension.ItemTypeName} Current", () =>
                {
                    AggressiveInlining();
                    WriteLine("get => _enumerator.Current;");
                });
                WriteLine();
                WriteLine("object global::System.Collections.IEnumerator.Current => Current;");
                WriteLine();

                AggressiveInlining();
                Block("public bool MoveNext()", () =>
                {
                    WriteLine("return _enumerator.MoveNext();");
                });
                WriteLine();

                Block("public void Reset()", () =>
                {
                    WriteLine("_enumerator.Reset();");
                });
                WriteLine();

                Block("public void Dispose()", () =>
                {
                    WriteLine("_enumerator.Dispose();");
                });
            });
        }

        private static string GetUnsafePointerExpression(QueryExtensionData queryExtension)
        {
            var collectionType = queryExtension.CollectionTypeName;
            if (collectionType.StartsWith("global::Unity.Collections.NativeArray<"))
            {
                return "global::Unity.Collections.LowLevel.Unsafe.NativeArrayUnsafeUtility.GetUnsafeReadOnlyPtr(_collection)";
            }

            if (collectionType.StartsWith("global::Unity.Collections.NativeList<"))
            {
                return $"global::Unity.Collections.LowLevel.Unsafe.NativeListUnsafeUtility.GetUnsafePtr<{queryExtension.ItemTypeName}>(_collection)";
            }

            if (collectionType.StartsWith("global::Unity.Collections.LowLevel.Unsafe.UnsafeList<") &&
                collectionType.Contains(".ReadOnly"))
            {
                return "_collection.Ptr";
            }

            if (collectionType.StartsWith("global::Unity.Collections.LowLevel.Unsafe.UnsafeList<"))
            {
                return "_collection.Ptr";
            }

            return "_collection.GetUnsafePtr()";
        }

        private static string GetElementAtExpression(QueryExtensionData queryExtension)
        {
            var collectionType = queryExtension.CollectionTypeName;
            if (collectionType.StartsWith("global::Unity.Collections.LowLevel.Unsafe.UnsafeList<") &&
                collectionType.Contains(".ReadOnly"))
            {
                return "_collection.Ptr[index]";
            }

            return "_collection[index]";
        }
    }
}
