namespace FireAlt.BLinq.Generators.Templates
{
    using System.Collections.Immutable;

    internal sealed class QueryCollectionExtensionsTemplate : TextTemplate
    {
        private readonly ImmutableArray<QueryExtensionData> queryExtensions;

        public QueryCollectionExtensionsTemplate(ImmutableArray<QueryExtensionData> queryExtensions)
        {
            this.queryExtensions = queryExtensions;
        }

        protected override void Render()
        {
            Header();
            Block("namespace FireAlt.BLinq", () =>
            {
                Block("public static partial class BLinqExtensions", () =>
                {
                    for (var i = 0; i < queryExtensions.Length; i++)
                    {
                        if (i != 0)
                        {
                            WriteLine();
                        }

                        QueryExtension(queryExtensions[i]);
                    }
                });
            });
        }

        private void Header()
        {
            WriteLine("// <auto-generated/>");
            WriteLine("#nullable enable");
            WriteLine();
        }

        private void QueryExtension(QueryExtensionData queryExtension)
        {
            var typeParameterList = queryExtension.TypeParameterNames.Length == 0
                ? string.Empty
                : $"<{string.Join(", ", queryExtension.TypeParameterNames)}>";
            var queryType = $"global::FireAlt.BLinq.Query<{queryExtension.EnumeratorTypeName}, {queryExtension.ItemTypeName}>";

            AggressiveInlining();
            WriteLine($"public static {queryType} AsQuery{typeParameterList}(this {queryExtension.CollectionTypeName} collection)");
            PushIndent();
            foreach (var constraintClause in queryExtension.ConstraintClauses)
            {
                WriteLine(constraintClause);
            }

            PopIndent();
            Block(() =>
            {
                if (queryExtension.LengthExpression.Length == 0)
                {
                    WriteLine($"return new {queryType}({queryExtension.EnumeratorExpression});");
                }
                else
                {
                    WriteLine($"return new {queryType}({queryExtension.EnumeratorExpression}, {queryExtension.LengthExpression});");
                }
            });
        }
    }
}
